plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: "impressum.html"
    values:
      sitemap: false
  - scope:
      path: "lehrer.html"
    values:
      sitemap: false
  - scope:
      path: "mitglieder"
    values:
      sitemap: false
  - scope:
      path: "mitglieder/"
    values:
      sitemap: false