const cards = [
  // ==========================================
  // 1. ALLTAG & GEGENSTÄNDE (50)
  // ==========================================
  { word: "APFEL", taboo: ["Obst", "Baum", "Rot", "Schneewittchen", "Kuchen"] },
  { word: "KAFFEE", taboo: ["Bohne", "Trinken", "Heiß", "Wach", "Espresso"] },
  { word: "SCHLÜSSEL", taboo: ["Schloss", "Tür", "Metall", "Auto", "Bund"] },
  { word: "SPIEGEL", taboo: ["Reflexion", "Glas", "Bad", "Sehen", "Eitel"] },
  { word: "SCHIRM", taboo: ["Regen", "Nass", "Wetter", "Aufspannen", "Schutz"] },
  { word: "KISSEN", taboo: ["Bett", "Schlafen", "Weich", "Kopf", "Couch"] },
  { word: "UHR", taboo: ["Zeit", "Armband", "Zeiger", "Spät", "Stunde"] },
  { word: "BRILLE", taboo: ["Sehen", "Augen", "Nase", "Gläser", "Optiker"] },
  { word: "KUGELSCHREIBER", taboo: ["Stift", "Schreiben", "Tinte", "Blau", "Papier"] },
  { word: "PORTEMONNAIE", taboo: ["Geld", "Börse", "Scheine", "Karten", "Leder"] },
  { word: "KERZE", taboo: ["Wachs", "Feuer", "Docht", "Licht", "Geburtstag"] },
  { word: "TASCHENLAMPE", taboo: ["Licht", "Dunkel", "Batterie", "Strahl", "Nacht"] },
  { word: "STAUBSAUGER", taboo: ["Dreck", "Saugen", "Boden", "Teppich", "Haushalt"] },
  { word: "ZAHNBÜRSTE", taboo: ["Putzen", "Mund", "Pasta", "Morgens", "Sauber"] },
  { word: "HANDTUCH", taboo: ["Bad", "Trocken", "Nass", "Duschen", "Strand"] },
  { word: "SEIFE", taboo: ["Hände", "Waschen", "Schaum", "Duft", "Bad"] },
  { word: "KAMM", taboo: ["Haare", "Kämmen", "Frisur", "Kopf", "Zähne"] },
  { word: "FÖHN", taboo: ["Haare", "Luft", "Trocknen", "Heiß", "Bad"] },
  { word: "SCHERE", taboo: ["Schneiden", "Papier", "Friseur", "Klinge", "Basteln"] },
  { word: "MÜLLTONNE", taboo: ["Abfall", "Dreck", "Eimer", "Plastik", "Stinken"] },
  { word: "MÜNZE", taboo: ["Geld", "Kleingeld", "Metall", "Rund", "Cent"] },
  { word: "GÜRTEL", taboo: ["Hose", "Schnalle", "Leder", "Halten", "Taillens"] },
  { word: "RUCKSACK", taboo: ["Rücken", "Tasche", "Tragen", "Schule", "Wandern"] },
  { word: "KOFFER", taboo: ["Reisen", "Urlaub", "Packen", "Kleidung", "Flughafen"] },
  { word: "TEPPICH", taboo: ["Boden", "Wolle", "Muster", "Fliegen", "Wohnzimmer"] },
  { word: "KALTER KAFFEE", taboo: ["Alt", "Tasse", "Trinken", "Eis", "Morgen"] },
  { word: "LICHTSCHALTER", taboo: ["Drücken", "An", "Aus", "Wand", "Dunkel"] },
  { word: "PFANNE", taboo: ["Kochen", "Braten", "Herd", "Küchen", "Öl"] },
  { word: "TOPF", taboo: ["Kochen", "Wasser", "Deckel", "Suppe", "Herd"] },
  { word: "GABEL", taboo: ["Essen", "Besteck", "Zacken", "Messer", "Pickel"] },
  { word: "LÖFFEL", taboo: ["Suppe", "Essen", "Besteck", "Rund", "Müsli"] },
  { word: "MESSER", taboo: ["Schneiden", "Scharf", "Besteck", "Klinge", "Küche"] },
  { word: "TELLER", taboo: ["Essen", "Porzellan", "Rund", "Tisch", "Spülen"] },
  { word: "TASSE", taboo: ["Tee", "Kaffee", "Trinken", "Henkel", "Porzellan"] },
  { word: "GLAS", taboo: ["Wasser", "Trinken", "Durchsichtig", "Zerbrechlich", "Flasche"] },
  { word: "FLASCHE", taboo: ["Wasser", "Deckel", "Trinken", "Plastik", "Glas"] },
  { word: "GIESSEIMER", taboo: ["Garten", "Pflanzen", "Wasser", "Blumen", "Gießen"] },
  { word: "BÜGELEISEN", taboo: ["Falten", "Hemd", "Heiß", "Dampf", "Wäsche"] },
  { word: "WÄSCHESTÄNDER", taboo: ["Trocknen", "Nass", "Kleidung", "Aufhängen", "Leine"] },
  { word: "KISSENBEZUG", taboo: ["Bett", "Waschen", "Stoff", "Schlafen", "Bunt"] },
  { word: "BETTENLAGER", taboo: ["Matratze", "Schlafen", "Decke", "Nacht", "Zimmer"] },
  { word: "WECKER", taboo: ["Morgens", "Zeit", "Klingeln", "Aufstehen", "Uhr"] },
  { word: "BILDERRAHMEN", taboo: ["Foto", "Wand", "Erinnerung", "Glas", "Holz"] },
  { word: "LEITER", taboo: ["Hoch", "Klettern", "Sprossen", "Steigen", "Wand"] },
  { word: "SCHAUFEL", taboo: ["Erde", "Garten", "Sand", "Graben", "Schnee"] },
  { word: "BESEN", taboo: ["Fegen", "Boden", "Dreck", "Kehren", "Hexe"] },
  { word: "ZÜNDHOLZ", taboo: ["Feuer", "Anzünden", "Schachtel", "Holz", "Rauch"] },
  { word: "FEUERZEUG", taboo: ["Gas", "Flamme", "Rauchen", "Kerze", "Anzünden"] },
  { word: "KOPFHÖRER", taboo: ["Musik", "Ohren", "Kabel", "Hören", "Sound"] },
  { word: "GARTENSCHLAUCH", taboo: ["Wasser", "Gießen", "Grün", "Spritzen", "Sommer"] },

  // ==========================================
  // 2. ORTE & REISEN (50)
  // ==========================================
  { word: "STRAND", taboo: ["Meer", "Sand", "Urlaub", "Sonne", "Palme"] },
  { word: "KINO", taboo: ["Film", "Popcorn", "Leinwand", "Sitz", "Schauspieler"] },
  { word: "FLUGHAFEN", taboo: ["Flugzeug", "Reisen", "Koffer", "Fliegen", "Gate"] },
  { word: "BIBLIOTHEK", taboo: ["Buch", "Lesen", "Stille", "Ausleihen", "Regal"] },
  { word: "SUPERMARKT", taboo: ["Einkaufen", "Wagen", "Kasse", "Lebensmittel", "Bezahlen"] },
  { word: "KRANKENHAUS", taboo: ["Arzt", "Patient", "Bett", "Gesundheit", "Spritze"] },
  { word: "BOHNE", taboo: ["Kaffee", "Grün", "Gemüse", "Eintopf", "Pflanze"] },
  { word: "BAHNHOF", taboo: ["Zug", "Gleis", "Fahrkarte", "Verspätung", "Reisen"] },
  { word: "HOTEL", taboo: ["Zimmer", "Übernachtung", "Urlaub", "Bett", "Rezeption"] },
  { word: "MUSEUM", taboo: ["Kunst", "Ausstellung", "Bilder", "Geschichte", "Alt"] },
  { word: "RESTAURANT", taboo: ["Essen", "Kellner", "Karte", "Bestellen", "Tisch"] },
  { word: "PARK", taboo: ["Bäume", "Wiese", "Spazieren", "Bank", "Grün"] },
  { word: "ZOO", taboo: ["Tiere", "Käfig", "Gehege", "Löwe", "Kinder"] },
  { word: "SCHULE", taboo: ["Lernen", "Lehrer", "Klasse", "Schüler", "Unterricht"] },
  { word: "UNIVERSITÄT", taboo: ["Studieren", "Professor", "Campus", "Vorlesung", "Mensa"] },
  { word: "TANTSTADT", taboo: ["Disco", "Musik", "Tanzen", "Nacht", "Party"] },
  { word: "SCHLOSS", taboo: ["König", "Prinzessin", "Alt", "Burg", "Turm"] },
  { word: "INSEL", taboo: ["Wasser", "Meer", "Rund", "Strand", "Land"] },
  { word: "WÜSTE", taboo: ["Sand", "Heiß", "Kamel", "Trocken", "Sonne"] },
  { word: "GEBIRGE", taboo: ["Berge", "Schnee", "Klettern", "Hoch", "Gipfel"] },
  { word: "CAMPINGPLATZ", taboo: ["Zelt", "Wohnmobil", "Draußen", "Urlaub", "Natur"] },
  { word: "FREIZEITPARK", taboo: ["Achterbahn", "Karussell", "Spaß", "Eintritt", "Kinder"] },
  { word: "SCHIMMABUTIK", taboo: ["Wasser", "Schwimmen", "Becken", "Rutsche", "Tauchen"] },
  { word: "TANKSTELLE", taboo: ["Benzin", "Auto", "Diesel", "Tanken", "Zapfsäule"] },
  { word: "BÄCKEREI", taboo: ["Brot", "Brötchen", "Kuchen", "Mehl", "Verkaufen"] },
  { word: "APOTHEKE", taboo: ["Medizin", "Rezept", "Krank", "Tabletten", "Kreuz"] },
  { word: "HAFEN", taboo: ["Schiff", "Boot", "Wasser", "Kran", "Meer"] },
  { word: "STADION", taboo: ["Fußball", "Fans", "Spiel", "Plätze", "Rasen"] },
  { word: "THEATER", taboo: ["Bühne", "Schauspieler", "Drama", "Stück", "Vorstellung"] },
  { word: "OPERNHAUS", taboo: ["Singen", "Musik", "Bühne", "Klassik", "Orchester"] },
  { word: "FRIEDHOF", taboo: ["Gräber", "Tot", "Blumen", "Trauer", "Steine"] },
  { word: "KIRCHE", taboo: ["Glaube", "Gott", "Glocke", "Turm", "Pfarrer"] },
  { word: "RATHAUS", taboo: ["Bürgermeister", "Stadt", "Verwaltung", "Amt", "Politik"] },
  { word: "POLIZEISTATION", taboo: ["Polizei", "Zelle", "Verbrechen", "Anzeige", "Sicherheit"] },
  { word: "POSTAMTSSTELLE", taboo: ["Brief", "Paket", "Marke", "Senden", "Gelb"] },
  { word: "DRUCKEREI", taboo: ["Papier", "Drucken", "Tinte", "Buch", "Zeitung"] },
  { word: "FRISIERSALON", taboo: ["Haare", "Schneiden", "Friseur", "Waschen", "Spiegel"] },
  { word: "FITNESSSTUDIO", taboo: ["Sport", "Training", "Muskeln", "Geräte", "Schwitzen"] },
  { word: "KLEINGARTEN", taboo: ["Parzelle", "Garten", "Blumen", "Zaun", "Laube"] },
  { word: "AUTOWERKSTATT", taboo: ["Reparatur", "Auto", "Mechaniker", "Reifen", "Motor"] },
  { word: "WASCHSTRASSE", taboo: ["Auto", "Waschen", "Sauber", "Wasser", "Bürsten"] },
  { word: "MARKTPLATZ", taboo: ["Kaufen", "Stände", "Frisch", "Gemüse", "Stadt"] },
  { word: "SPIELPLATZ", taboo: ["Kinder", "Schaukel", "Rutsche", "Sandkasten", "Spielen"] },
  { word: "CLUB", taboo: ["Tanzen", "Nacht", "Musik", "DJ", "Trinken"] },
  { word: "BAR", taboo: ["Cocktail", "Bier", "Trinken", "Abend", "Tresen"] },
  { word: "CAFÉ", taboo: ["Kaffee", "Kuchen", "Tasse", "Tisch", "Trinken"] },
  { word: "PIZZERIA", taboo: ["Pizza", "Italien", "Essen", "Ofen", "Pasta"] },
  { word: "IMBISS", taboo: ["Fastfood", "Pommes", "Wurst", "Schnell", "Essen"] },
  { word: "SKIGEBIET", taboo: ["Schnee", "Ski", "Berg", "Lift", "Kalt"] },
  { word: "TAL", taboo: ["Berge", "Unten", "Fluss", "Zwischen", "Grün"] },

  // ==========================================
  // 3. TECHNIK & MEDIA (50)
  // ==========================================
  { word: "INTERNET", taboo: ["WLAN", "Netzwerk", "Online", "Google", "Browser"] },
  { word: "SMARTPHONE", taboo: ["Handy", "App", "Anrufen", "Display", "Touch"] },
  { word: "PODCAST", taboo: ["Hören", "Audio", "Mikrofon", "Folge", "Spotify"] },
  { word: "GAMEBOY", taboo: ["Nintendo", "Konsole", "Spielen", "Retro", "Tetris"] },
  { word: "ROBOTER", taboo: ["Maschine", "Künstlich", "Metall", "Zukunft", "Automatisch"] },
  { word: "FERNSEHER", taboo: ["TV", "Bildschirm", "Programm", "Kanal", "Fernbedienung"] },
  { word: "LAPTOP", taboo: ["Computer", "Tastatur", "Tragbar", "Bildschirm", "Maus"] },
  { word: "TABLET", taboo: ["Touch", "iPad", "Display", "Bildschirm", "Flach"] },
  { word: "DRUCKER", taboo: ["Papier", "Tinte", "Drucken", "Scannen", "Ausgeben"] },
  { word: "TASTATUR", taboo: ["Schreiben", "Tasten", "Computer", "Buchstaben", "Tippen"] },
  { word: "MAUS", taboo: ["Klicken", "Cursor", "Computer", "Pad", "Hand"] },
  { word: "BILDSCHIRM", taboo: ["Monitor", "Sehen", "Display", "Flach", "Anzeige"] },
  { word: "KABELDATEN", taboo: ["Verbindung", "Strom", "USB", "Laden", "Stecker"] },
  { word: "KAMERA", taboo: ["Foto", "Bild", "Knipsen", "Linse", "Video"] },
  { word: "LAUTSPRECHER", taboo: ["Musik", "Sound", "Laut", "Box", "Hören"] },
  { word: "MICROSD", taboo: ["Speicher", "Karte", "Klein", "Fotos", "Handy"] },
  { word: "WLAN", taboo: ["Internet", "Kabellos", "Router", "Verbindung", "Netz"] },
  { word: "BLUETOOTH", taboo: ["Kabellos", "Verbinden", "Musik", "Signal", "Blau"] },
  { word: "APP", taboo: ["Handy", "Anwendung", "Download", "Store", "Icon"] },
  { word: "BEAMER", taboo: ["Projektor", "Wand", "Film", "Licht", "Groß"] },
  { word: "DRONE", taboo: ["Fliegen", "Kamera", "Luft", "Fernsteuerung", "Propeller"] },
  { word: "VIRTUAL REALITY", taboo: ["Brille", "VR", "Virtuell", "3D", "Game"] },
  { word: "SMARTWATCH", taboo: ["Uhr", "Armband", "Schritte", "Digital", "Handy"] },
  { word: "USB-STICK", taboo: ["Speicher", "Daten", "Klein", "Stecker", "PC"] },
  { word: "FESTPLATTE", taboo: ["Speicher", "Daten", "PC", "Gigabyte", "Extern"] },
  { word: "POWERBANK", taboo: ["Akku", "Laden", "Unterwegs", "Strom", "Handy"] },
  { word: "MUSEUMSTÜCK", taboo: ["Alt", "Geschichte", "Ausstellung", "Sammlung", "Objekt"] },
  { word: "STREAMING", taboo: ["Netflix", "Spotify", "Online", "Schauen", "Video"] },
  { word: "SOCIAL MEDIA", taboo: ["Instagram", "TikTok", "Post", "Likes", "Follower"] },
  { word: "E-MAIL", taboo: ["Nachricht", "Senden", "Postfach", "Digital", "Internet"] },
  { word: "KÜNSTLICHE INTELLIGENZ", taboo: ["AI", "KI", "Schlau", "Computer", "ChatGPT"] },
  { word: "ALGORITHMUS", taboo: ["Code", "Mathematik", "Regeln", "Computer", "Logik"] },
  { word: "DATENBANK", taboo: ["Speichern", "Tabellen", "Daten", "SQL", "Information"] },
  { word: "PASSWORT", taboo: ["Geheim", "Sicherheit", "Login", "Kombination", "Eingabe"] },
  { word: "FEUERWALL", taboo: ["Schutz", "Sicherheit", "Netzwerk", "Sperre", "PC"] },
  { word: "VIRUS", taboo: ["Schädling", "Krank", "PC", "Gefahr", "Antivirus"] },
  { word: "SERVERSCHRANK", taboo: ["Netzwerk", "Daten", "Groß", "Internet", "Hosting"] },
  { word: "WEBCAM", taboo: ["Kamera", "Video", "Call", "Zoom", "PC"] },
  { word: "MIKROFON", taboo: ["Sprechen", "Stimme", "Aufnahme", "Audio", "Singen"] },
  { word: "KABELFERNSEHEN", taboo: ["TV", "Anschluss", "Sender", "Signal", "Dose"] },
  { word: "SATELIT", taboo: ["Weltall", "Signal", "Orbit", "TV", "Schüssel"] },
  { word: "ELEKTROAUTO", taboo: ["Strom", "Akku", "Laden", "Tesla", "Fahren"] },
  { word: "SOLARZELLE", taboo: ["Sonne", "Strom", "Dach", "Energie", "Panel"] },
  { word: "3D-DRUCKER", taboo: ["Plastik", "Machen", "Schichten", "Drucken", "Modell"] },
  { word: "E-BOOK READER", taboo: ["Buch", "Lesen", "Kindle", "Digital", "Bildschirm"] },
  { word: "KASSETTE", taboo: ["Alt", "Musik", "Band", "Spulen", "Radio"] },
  { word: "SCHALLPLATTE", taboo: ["Vinyl", "Musik", "Schwarz", "Nadel", "Drehen"] },
  { word: "CD", taboo: ["Disc", "Musik", "Silber", "Rund", "Laser"] },
  { word: "DVD", taboo: ["Film", "Disc", "Player", "Hülle", "Video"] },
  { word: "RADIO", taboo: ["Hören", "Sender", "Musik", "Nachrichten", "Auto"] },

  // ==========================================
  // 4. ESSEN & TRINKEN (50)
  // ==========================================
  { word: "PIZZA", taboo: ["Käse", "Italien", "Teig", "Ofen", "Salami"] },
  { word: "SCHOKOLADE", taboo: ["Süß", "Kakao", "Tafel", "Braun", "Zucker"] },
  { word: "NUDELN", taboo: ["Pasta", "Italien", "Kochen", "Spaghetti", "Soße"] },
  { word: "BURGER", taboo: ["Fleisch", "Fastfood", "Brot", "Pommes", "Ketchup"] },
  { word: "EISCREME", taboo: ["Kalt", "Sommer", "Waffel", "Kugel", "Süß"] },
  { word: "POMMES", taboo: ["Kartoffel", "Frittieren", "Salz", "Ketchup", "Majo"] },
  { word: "SUPPE", taboo: ["Löffel", "Flüssig", "Heiß", "Topf", "Gemüse"] },
  { word: "SALAT", taboo: ["Grün", "Blätter", "Gesund", "Dressing", "Gemüse"] },
  { word: "BROT", taboo: ["Scheibe", "Bäcker", "Teig", "Kruste", "Butter"] },
  { word: "KÄSE", taboo: ["Milch", "Gelb", "Löcher", "Kuh", "Scheibe"] },
  { word: "SCHINKEN", taboo: ["Schwein", "Fleisch", "Brotaufstrich", "Räuchern", "Pizza"] },
  { word: "EI", taboo: ["Huhn", "Schale", "Dotter", "Kochen", "Frühstück"] },
  { word: "MILCH", taboo: ["Kuh", "Weiß", "Trinken", "Müsli", "Glas"] },
  { word: "WASSER", taboo: ["Trinken", "Durst", "Nass", "Flasche", "Sprudel"] },
  { word: "SAFT", taboo: ["Frucht", "Orangen", "Apfel", "Süß", "Trinken"] },
  { word: "TEE", taboo: ["Beutel", "Heiß", "Wasser", "Trinken", "Kräuter"] },
  { word: "BIER", taboo: ["Hopfen", "Alkohol", "Flasche", "Brauerei", "Schaum"] },
  { word: "WEIN", taboo: ["Trauben", "Flasche", "Rot", "Weiß", "Glas"] },
  { word: "COCKTAIL", taboo: ["Alkohol", "Mixen", "Glas", "Eis", "Bar"] },
  { word: "KUCHEN", taboo: ["Geburtstag", "Backen", "Süß", "Stück", "Kerze"] },
  { word: "TORTE", taboo: ["Creme", "Geburtstag", "Schichten", "Backen", "Süß"] },
  { word: "KEKS", taboo: ["Dose", "Knusprig", "Schokolade", "Teig", "Backen"] },
  { word: "HONIG", taboo: ["Biene", "Süß", "Gelb", "Glasing", "Brot"] },
  { word: "MARMELADE", taboo: ["Frucht", "Brot", "Frühstück", "Süß", "Glas"] },
  { word: "BUTTER", taboo: ["Brot", "Gelb", "Fett", "Milch", "Streichen"] },
  { word: "JOGHURT", taboo: ["Milch", "Löffel", "Becher", "Frucht", "Weiß"] },
  { word: "REIS", taboo: ["Korn", "Asien", "Weiß", "Kochen", "Beilage"] },
  { word: "KARTOFFEL", taboo: ["Erde", "Knolle", "Pommes", "Püree", "Kochen"] },
  { word: "TOMATE", taboo: ["Rot", "Gemüse", "Soße", "Salat", "Ketchup"] },
  { word: "GURKE", taboo: ["Grün", "Salat", "Lang", "Wasser", "Gemüse"] },
  { word: "KAROTTE", taboo: ["Orange", "Hase", "Gemüse", "Knackig", "Erde"] },
  { word: "ZWIEBEL", taboo: ["Weinen", "Schneiden", "Scharf", "Kochen", "Gemüse"] },
  { word: "KNOBLAUCH", taboo: ["Riechen", "Zehe", "Scharf", "Kochen", "Mund"] },
  { word: "PILZE", taboo: ["Wald", "Sammeln", "Hut", "Champignon", "Steinpilz"] },
  { word: "ERDBEERE", taboo: ["Rot", "Frucht", "Sommer", "Süß", "Marmelade"] },
  { word: "BANANE", taboo: ["Gelb", "Affe", "Krumm", "Schale", "Frucht"] },
  { word: "ZITRONE", taboo: ["Gelb", "Sauer", "Frucht", "Saft", "Schale"] },
  { word: "ANANAS", taboo: ["Süß", "Gelb", "Krone", "Hawaii", "Frucht"] },
  { word: "WASSERMELONE", taboo: ["Grün", "Rot", "Kerne", "Sommer", "Groß"] },
  { word: "NUSS", taboo: ["Schale", "Knacken", "Eichhörnchen", "Baum", "Essen"] },
  { word: "POPCORN", taboo: ["Kino", "Mais", "Süß", "Salzig", "Snack"] },
  { word: "CHIPS", taboo: ["Tüte", "Kartoffel", "Knusprig", "Salzig", "Snack"] },
  { word: "GUMMIBÄRCHEN", taboo: ["Haribo", "Süß", "Gelatine", "Bunt", "Tüte"] },
  { word: "DÖNER", taboo: ["Fleisch", "Brot", "Fladen", "Soße", "Zwiebeln"] },
  { word: "SUSHI", taboo: ["Fisch", "Reis", "Japan", "Rolle", "Stäbchen"] },
  { word: "STEAK", taboo: ["Fleisch", "Rind", "Grill", "Braten", "Blutig"] },
  { word: "BRATWURST", taboo: ["Grill", "Senf", "Fleisch", "Bude", "Semmel"] },
  { word: "SUPPENGRÜN", taboo: ["Gemüse", "Topf", "Kochen", "Möhre", "Sellerie"] },
  { word: "MÜSLI", taboo: ["Haferflocken", "Milch", "Frühstück", "Schüssel", "Obst"] },
  { word: "PANCAKE", taboo: ["Pfannkuchen", "Ahornsirup", "USA", "Teig", "Frühstück"] },

  // ==========================================
  // 5. NATUR & TIERE (50)
  // ==========================================
  { word: "PINGUIN", taboo: ["Vogel", "Kalt", "Eis", "Fliegen", "Schwarz"] },
  { word: "VULKAN", taboo: ["Lava", "Berg", "Ausbruch", "Heiß", "Magma"] },
  { word: "REGENBOGEN", taboo: ["Farben", "Sonne", "Regen", "Himmel", "Bunt"] },
  { word: "GEPARD", taboo: ["Schnell", "Afrika", "Katze", "Flecken", "Rennen"] },
  { word: "WALD", taboo: ["Bäume", "Grün", "Tiere", "Holz", "Natur"] },
  { word: "HUND", taboo: ["Bellen", "Haustier", "Leine", "Treue", "Pfote"] },
  { word: "KATZE", taboo: ["Miau", "Schnurren", "Haustier", "Maus", "Fell"] },
  { word: "PFERD", taboo: ["Reiten", "Mähne", "Huf", "Sattel", "Stall"] },
  { word: "KUH", taboo: ["Milch", "Wiese", "Muh", "Fleck", "Gras"] },
  { word: "SCHAF", taboo: ["Wolle", "Mäh", "Wiese", "Weiß", "Herde"] },
  { word: "SCHWEIN", taboo: ["Rosa", "Matsch", "Oink", "Stall", "Fleisch"] },
  { word: "EULE", taboo: ["Nacht", "Vogel", "Große Augen", "Weise", "Uhu"] },
  { word: "ADLER", taboo: ["Vogel", "Fliegen", "Himmel", "Schnabel", "Greifvogel"] },
  { word: "PAPAGEI", taboo: ["Bunt", "Sprechen", "Vogel", "Feder", "Piraten"] },
  { word: "DELFIN", taboo: ["Meer", "Wasser", "Schlau", "Säugetier", "Springen"] },
  { word: "HAI", taboo: ["Fisch", "Zähne", "Meer", "Gefährlich", "Flosse"] },
  { word: "WAL", taboo: ["Groß", "Meer", "Ozean", "Blasen", "Säugetier"] },
  { word: "ELEFANT", taboo: ["Rüssel", "Groß", "Grau", "Stoßzahn", "Afrika"] },
  { word: "GIRAFFE", taboo: ["Hals", "Lang", "Afrika", "Flecken", "Baum"] },
  { word: "LÖWE", taboo: ["König", "Mähne", "Brüllen", "Afrika", "Raubkatze"] },
  { word: "TIGER", taboo: ["Streifen", "Orange", "Katze", "Dschungel", "Raubtier"] },
  { word: "BÄR", taboo: ["Honig", "Wald", "Braungrau", "Winterschlaf", "Pelz"] },
  { word: "WOLF", taboo: ["Heulen", "Rudel", "Mond", "Wald", "Hund"] },
  { word: "FUCHS", taboo: ["Rot", "Schlau", "Schwanz", "Wald", "Gans"] },
  { word: "HASE", taboo: ["Löffel", "Ostern", "Karotte", "Hüpfen", "Fell"] },
  { word: "EICHHÖRNCHEN", taboo: ["Nuss", "Baum", "Klettern", "Schwanz", "Buschig"] },
  { word: "SCHLANGE", taboo: ["Kriechen", "Gift", "Haut", "Zischen", "Beine"] },
  { word: "FROSCH", taboo: ["Grün", "Teich", "Quaken", "Hüpfen", "Fliege"] },
  { word: "BIENE", taboo: ["Honig", "Stacheln", "Gelb", "Blume", "Insekt"] },
  { word: "SCHMETTERLING", taboo: ["Flügel", "Bunt", "Raupe", "Fliegen", "Blume"] },
  { word: "AMEISE", taboo: ["Klein", "Fleißig", "Haufen", "Krabbeln", "Insekt"] },
  { word: "SPINNE", taboo: ["Netz", "Beine", "Acht", "Angst", "Krabbeln"] },
  { word: "KROKODIL", taboo: ["Reptil", "Zähne", "Fluss", "Grün", "Panzer"] },
  { word: "SCHILDKRÖTE", taboo: ["Panzer", "Langsam", "Alt", "Ei", "Reptil"] },
  { word: "KAMEL", taboo: ["Höcker", "Wüste", "Reiten", "Sand", "Durst"] },
  { word: "KÄNGURU", taboo: ["Beutel", "Australien", "Hüpfen", "Springen", "Schwanz"] },
  { word: "KOALA", taboo: ["Eukalyptus", "Australien", "Baum", "Schlafen", "Bär"] },
  { word: "FLUSS", taboo: ["Wasser", "Strömung", "Ufer", "Brücke", "Meer"] },
  { word: "SEE", taboo: ["Wasser", "Schwimmen", "Ufer", "Fische", "Boot"] },
  { word: "OZEAN", taboo: ["Meer", "Wasser", "Groß", "Wellen", "Salz"] },
  { word: "SONNE", taboo: ["Heiß", "Gelb", "Himmel", "Tag", "Licht"] },
  { word: "MOND", taboo: ["Nacht", "Himmel", "Krater", "Rund", "Scheinen"] },
  { word: "STERN", taboo: ["Nacht", "Himmel", "Funkeln", "Licht", "Galaxie"] },
  { word: "WOLKE", taboo: ["Himmel", "Weiß", "Regen", "Flauschig", "Wetter"] },
  { word: "BLITZ", taboo: ["Donner", "Gewitter", "Himmel", "Licht", "Sturm"] },
  { word: "DONNER", taboo: ["Gewitter", "Laut", "Blitz", "Himmel", "Geräusch"] },
  { word: "SCHNEE", taboo: ["Kalt", "Weiß", "Winter", "Flocke", "Eis"] },
  { word: "EISBERG", taboo: ["Kalt", "Ozean", "Schwimmen", "Spitze", "Titanic"] },
  { word: "BLUME", taboo: ["Duft", "Farbe", "Garten", "Wachsen", "Vase"] },
  { word: "BAUM", taboo: ["Blätter", "Holz", "Stamm", "Wald", "Grün"] },

  // ==========================================
  // 6. FREIZEIT & SPORT (50)
  // ==========================================
  { word: "FUSSBALL", taboo: ["Tor", "Rasen", "Elfmeter", "Kicken", "Ball"] },
  { word: "GITARRE", taboo: ["Saiten", "Musik", "Instrument", "Verstärker", "Zupfen"] },
  { word: "ZAUBERER", taboo: ["Magie", "Hut", "Trick", "Stab", "Harry Potter"] },
  { word: "MONOPOLY", taboo: ["Spiel", "Geld", "Straßen", "Würfel", "Gefängnis"] },
  { word: "SCHACH", taboo: ["König", "Brett", "Schwarz", "Weiß", "Matt"] },
  { word: "TENNIS", taboo: ["Schläger", "Ball", "Netz", "Gelb", "Aufschlag"] },
  { word: "BASKETBALL", taboo: ["Korb", "Ball", "Werfen", "USA", "Dribbeln"] },
  { word: "HANDBALL", taboo: ["Werfen", "Tor", "Halle", "Ball", "Harz"] },
  { word: "VOLLEYBALL", taboo: ["Netz", "Strand", "Pritschen", "Schlagen", "Ball"] },
  { word: "GOLF", taboo: ["Schläger", "Loch", "Ball", "Grün", "Caddy"] },
  { word: "SCHWIMMEN", taboo: ["Wasser", "Becken", "Kraulen", "Nass", "Sport"] },
  { word: "JOGGEN", taboo: ["Laufen", "Schuhe", "Park", "Fit", "Ausdauer"] },
  { word: "RADFAHREN", taboo: ["Fahrrad", "Helme", "Pedale", "Kette", "Räder"] },
  { word: "SKIFAHREN", taboo: ["Schnee", "Berg", "Piste", "Kalt", "Lift"] },
  { word: "SNOWBOARD", taboo: ["Schnee", "Brett", "Piste", "Winter", "Fahren"] },
  { word: "SCHLITTSCHUH", taboo: ["Eis", "Kufe", "Winter", "Halle", "Laufen"] },
  { word: "SURFEN", taboo: ["Wellen", "Brett", "Meer", "Ozean", "Wasser"] },
  { word: "KLETTERN", taboo: ["Berg", "Wand", "Seil", "Haken", "Hoch"] },
  { word: "WANDERN", taboo: ["Berge", "Schuhe", "Rucksack", "Weg", "Natur"] },
  { word: "ANGELN", taboo: ["Fisch", "Rute", "Haken", "Wasser", "Teich"] },
  { word: "TANZEN", taboo: ["Musik", "Schritte", "Rhythmus", "Paar", "Ballett"] },
  { word: "SINGEN", taboo: ["Stimme", "Lied", "Mikrofon", "Musik", "Chor"] },
  { word: "KLAVIER", taboo: ["Tasten", "Schwarz", "Weiß", "Flügel", "Musik"] },
  { word: "SCHLAGZEUG", taboo: ["Trommel", "Becken", "Stöcke", "Laut", "Rhythmus"] },
  { word: "FLÖTE", taboo: ["Blasen", "Holz", "Löcher", "Instrument", "Musik"] },
  { word: "GEIGE", taboo: ["Saiten", "Bogen", "Schulter", "Klassik", "Instrument"] },
  { word: "MALEN", taboo: ["Pinsel", "Farbe", "Bild", "Künstler", "Leinwand"] },
  { word: "STRICKEN", taboo: ["Wolle", "Nadeln", "Pulli", "Oma", "Garn"] },
  { word: "GÄRTNERN", taboo: ["Pflanzen", "Blumen", "Erde", "Garten", "Gießen"] },
  { word: "KOCHEN", taboo: ["Topf", "Essen", "Rezept", "Herd", "Küche"] },
  { word: "BACKEN", taboo: ["Ofen", "Kuchen", "Teig", "Mehl", "Zucker"] },
  { word: "LESEN", taboo: ["Buch", "Seiten", "Text", "Bibliothek", "Augen"] },
  { word: "GAMING", taboo: ["Zocken", "Konsole", "PC", "Spiel", "Controller"] },
  { word: "PUZZLE", taboo: ["Teile", "Zusammenbauen", "Geduld", "Bild", "Legespiel"] },
  { word: "DART", taboo: ["Pfeile", "Scheibe", "Werfen", "Mitte", "Kneipe"] },
  { word: "BOWLING", taboo: ["Kugel", "Pins", "Bahnen", "Schuhe", "Strike"] },
  { word: "BILLARD", taboo: ["Kugeln", "Köer", "Tisch", "Grün", "Loch"] },
  { word: "TISCHTENNIS", taboo: ["Platte", "Schläger", "Netz", "Ball", "Pingpong"] },
  { word: "BADMINTON", taboo: ["Federball", "Schläger", "Netz", "Werfen", "Luft"] },
  { word: "YOGA", taboo: ["Matte", "Entspannung", "Übung", "Dehnen", "Atmen"] },
  { word: "BOXEN", taboo: ["Handschuhe", "Ring", "Schlagen", "Kampf", "Knockout"] },
  { word: "KARATE", taboo: ["Gürtel", "Kampfsport", "Japan", "Schlagen", "Kick"] },
  { word: "REITEN", taboo: ["Pferd", "Sattel", "Stall", "Helm", "Galopp"] },
  { word: "FALLSCHIRMSPRUNG", taboo: ["Flugzeug", "Luft", "Springen", "Höhe", "Öffnen"] },
  { word: "BUNGEE", taboo: ["Seil", "Springen", "Tiefe", "Brücke", "Adrenalin"] },
  { word: "FOTOGRAFIEREN", taboo: ["Kamera", "Foto", "Bild", "Linse", "Motiv"] },
  { word: "MUSEUMSBEUCH", taboo: ["Kunst", "Bilder", "Ausstellung", "Kultur", "Ticket"] },
  { word: "FESTIVAL", taboo: ["Musik", "Zelt", "Bühne", "Bands", "Sommer"] },
  { word: "KONZERT", taboo: ["Bühne", "Musik", "Band", "Tickets", "Fans"] },
  { word: "KARAOKE", taboo: ["Singen", "Mikrofon", "Text", "Bildschirm", "Party"] },

  // ==========================================
  // 7. ABSTRAKTES & BERUFE (50)
  // ==========================================
  { word: "TRAUM", taboo: ["Schlafen", "Nacht", "REM", "Wunsch", "Gedanke"] },
  { word: "DETEKTIV", taboo: ["Lösen", "Spur", "Lupe", "Fall", "Polizei"] },
  { word: "PIRAT", taboo: ["Schiff", "Schatz", "Auge", "Kapitän", "Papagei"] },
  { word: "FEUERWEHR", taboo: ["Löschen", "Wasser", "Rot", "Tatütata", "Schlauch"] },
  { word: "ASTRONAUT", taboo: ["Weltall", "Mond", "Rakete", "Anzug", "Schwerelos"] },
  { word: "ARZT", taboo: ["Krankenhaus", "Gesundheit", "Stethoskop", "Praxis", "Rezept"] },
  { word: "LEHRER", taboo: ["Schule", "Unterricht", "Schüler", "Klasse", "Lernen"] },
  { word: "POLIZIST", taboo: ["Sicherheit", "Auto", "Sirene", "Waffe", "Verbrechen"] },
  { word: "PILOT", taboo: ["Flugzeug", "Fliegen", "Cockpit", "Himmel", "Airline"] },
  { word: "KÖCHIN", taboo: ["Küche", "Essen", "Restaurant", "Topf", "Kochen"] },
  { word: "BÄCKER", taboo: ["Brot", "Brötchen", "Ofen", "Früh", "Mehl"] },
  { word: "FRISEUR", taboo: ["Haare", "Schere", "Schneiden", "Kamm", "Kopf"] },
  { word: "ANWALT", taboo: ["Gericht", "Recht", "Gesetz", "Klage", "Verteidiger"] },
  { word: "RICHTER", taboo: ["Gericht", "Hammer", "Urteil", "Gesetz", "Robe"] },
  { word: "BÜRGERMEISTER", taboo: ["Stadt", "Rathaus", "Wahl", "Politik", "Chef"] },
  { word: "SCHAUSPIELER", taboo: ["Film", "Theater", "Rolle", "Hollywood", "Bühne"] },
  { word: "SÄNGER", taboo: ["Musik", "Stimme", "Lied", "Bühne", "Mikrofon"] },
  { word: "MALER", taboo: ["Farbe", "Pinsel", "Wand", "Bild", "Künstler"] },
  { word: "TISCHLER", taboo: ["Holz", "Möbel", "Säge", "Werkstatt", "Handwerk"] },
  { word: "ARCHITEKT", taboo: ["Haus", "Bauen", "Plan", "Zeichnen", "Gebäude"] },
  { word: "PROGRAMMIERER", taboo: ["Code", "Computer", "Software", "Entwickeln", "PC"] },
  { word: "JOURNALIST", taboo: ["Zeitung", "Artikel", "Schreiben", "Nachrichten", "Interview"] },
  { word: "FOTOGRAF", taboo: ["Foto", "Kamera", "Bild", "Studio", "Knipsen"] },
  { word: "TIERARZT", taboo: ["Tiere", "Krank", "Praxis", "Hund", "Katze"] },
  { word: "ZAHNARZT", taboo: ["Zähne", "Bohrer", "Mund", "Schmerzen", "Putzen"] },
  { word: "BAUARBEITER", taboo: ["Baustelle", "Helm", "Bauen", "Kran", "Stein"] },
  { word: "KASSANIERER", taboo: ["Supermarkt", "Geld", "Kasse", "Scannen", "Bezahlen"] },
  { word: "KELLNER", taboo: ["Restaurant", "Essen", "Bringt", "Trinkgeld", "Karte"] },
  { word: "GÄRTNER", taboo: ["Pflanzen", "Garten", "Blumen", "Rasen", "Erde"] },
  { word: "MÜLLWERKER", taboo: ["Abfall", "Tonne", "Auto", "Dreck", "Orange"] },
  { word: "LIEBE", taboo: ["Herz", "Gefühl", "Rot", "Kuss", "Partner"] },
  { word: "GLÜCK", taboo: ["Zufall", "Freude", "Kleeblatt", "Gewinn", "Schwein"] },
  { word: "ANGST", taboo: ["Dunkel", "Gefahr", "Schrecken", "Panik", "Herzklopfen"] },
  { word: "ZEIT", taboo: ["Uhr", "Stunde", "Vergehen", "Zukunft", "Vergangenheit"] },
  { word: "FRIEDEN", taboo: ["Taube", "Krieg", "Freiheit", "Kein Streit", "Welt"] },
  { word: "FREUNDSCHAFT", taboo: ["Kumpel", "Vertrauen", "Zusammen", "Gemeinsam", "Beste"] },
  { word: "GEHEIMNIS", taboo: ["Flüstern", "Niemand", "Sagen", "Versteckt", "Pscht"] },
  { word: "HOFFNUNG", taboo: ["Glaube", "Zukunft", "Wunsch", "Grün", "Positiv"] },
  { word: "WUT", taboo: ["Sauer", "Gefühl", "Schreien", "Rot", "Ärger"] },
  { word: "TRAUER", taboo: ["Weinen", "Traurig", "Verlust", "Tod", "Tränen"] },
  { word: "FREUDE", taboo: ["Lachen", "Glücklich", "Spaß", "Gefühl", "Lächeln"] },
  { word: "GERECHTIGKEIT", taboo: ["Fairess", "Gericht", "Gesetz", "Gleich", "Richtig"] },
  { word: "FREIHEIT", taboo: ["Egal", "Tun", "Keine Grenzen", "Fliegen", "Vogel"] },
  { word: "GEDÄCHTNIS", taboo: ["Erinnerung", "Kopf", "Gehirn", "Vergessen", "Merken"] },
  { word: "ZUKUNFT", taboo: ["Später", "Morgen", "Zeit", "Vorhersage", "Kommt"] },
  { word: "VERGANGENHEIT", taboo: ["Gestern", "Damals", "Geschichte", "Früher", "Zeit"] },
  { word: "IDEE", taboo: ["Einfall", "Kopf", "Glühbirne", "Gedanke", "Lösung"] },
  { word: "HUMOR", taboo: ["Lachen", "Witz", "Lustig", "Spaß", "Comedy"] },
  { word: "GEDULD", taboo: ["Warten", "Ruhig", "Zeit", "Ausdauer", "Langsam"] },
  { word: "MUT", taboo: ["Tapfer", "Angst", "Trauen", "Held", "Gefahr"] }
];